CREATE TABLE residential (
    location_id UUID REFERENCES locations(id) PRIMARY KEY,
    beds INTEGER,
    baths INTEGER,
    stories INTEGER,
    units INTEGER,
    num_bldgs INTEGER,
    above_sf DECIMAL NOT NULL,
    below_sf DECIMAL NOT NULL,
    finished_sf DECIMAL NOT NULL,
    has_garden_level BOOLEAN NOT NULL
);

CREATE TABLE neighborhood (
    id SMALLINT NOT NULL,
    name varchar(50)
);

INSERT INTO neighborhood (id, name) VALUES
    (1, 'ACADEMY'),
    (2, 'ARAPAHOE SQUARE'),
    (3, 'ATHMAR PARK'),
    (4, 'AURARIA'),
    (5, 'AVONDALE'),
    (6, 'BAKER'),
    (7, 'BALLPARK'),
    (8, 'BARNUM'),
    (9, 'BEAR VALLEY'),
    (10, 'BELCARO'),
    (11, 'BELMONT HTS'),
    (12, 'BERKELEY'),
    (13, 'BISCAYNE'),
    (14, 'BONNIE BRAE'),
    (15, 'BREAKERS'),
    (16, 'CAPITOL HILL'),
    (17, 'CAPITOL HILL S'),
    (18, 'CBD'),
    (19, 'CENTRAL PARK'),
    (20, 'CHAFFEE PARK'),
    (21, 'CHEESMAN PARK'),
    (22, 'CHERMONT'),
    (23, 'CHERRY CREEK'),
    (24, 'CHERRY POINT'),
    (25, 'CIVIC CENTER'),
    (26, 'CLAYTON'),
    (27, 'COLE'),
    (28, 'COLLEGE VIEW'),
    (29, 'COMMONS'),
    (30, 'CONGRESS PARK'),
    (31, 'CORNERSTONE'),
    (32, 'CORY MERRILL'),
    (33, 'COUNTRY CLUB'),
    (34, 'CREEKVW/SUNSET'),
    (35, 'CRESTMOOR'),
    (36, 'CRESTMOOR E'),
    (37, 'CRESTRIDGE'),
    (38, 'CURTIS PARK'),
    (39, 'DARTMOUTH HTS'),
    (40, 'DENVER TECH'),
    (41, 'E COLFAX (N)'),
    (42, 'E COLFAX (S)'),
    (43, 'E HARVEY PARK'),
    (44, 'E HIGHLAND'),
    (45, 'E SLOANS LAKE'),
    (46, 'EAST BAY'),
    (47, 'FIVE POINTS'),
    (48, 'FORT LOGAN'),
    (49, 'GATEWAY N'),
    (50, 'GLENBROOK'),
    (51, 'GLOBEVILLE'),
    (52, 'GODSMAN'),
    (53, 'GOLDSMITH'),
    (54, 'GOLDSMITH  W'),
    (55, 'GRANT RN/MARST'),
    (56, 'GREEN VALLEY'),
    (57, 'GUN CLUB'),
    (58, 'HALE/MAYFAIR'),
    (59, 'HAMPDEN HTS E'),
    (60, 'HAMPDEN HTS W'),
    (61, 'HARVEY PARK'),
    (62, 'HIGHLAND'),
    (63, 'HILLTOP'),
    (64, 'HILLTOP 6TH AV'),
    (65, 'HILLTOP DOWNS'),
    (66, 'HOLLY HILLS'),
    (67, 'HOLLY RIDGE'),
    (68, 'HUTCH/WILLOW P'),
    (69, 'HUTCHINSON HLS'),
    (70, 'INDIAN CREEK'),
    (71, 'INSPIRATION PT'),
    (72, 'JEFFERSON PARK'),
    (73, 'KENNEDY'),
    (74, 'LINCOLN PARK'),
    (75, 'LODO'),
    (76, 'LOWRY'),
    (77, 'LYNWOOD'),
    (78, 'MAR LEE'),
    (79, 'MONACO PKWY'),
    (80, 'MONTBELLO'),
    (81, 'MONTCLAIR'),
    (82, 'N CAPITOL HILL'),
    (83, 'N CHERRY CREEK'),
    (84, 'N CONGRESS PK'),
    (85, 'N COUNTRY CLUB'),
    (86, 'N GREEN VALLEY'),
    (87, 'N PARK HILL'),
    (88, 'N POLO CLUB'),
    (89, 'N SLOANS LAKE'),
    (90, 'N SPEER'),
    (91, 'N UNIVERSITY'),
    (92, 'NE PARK HILL'),
    (93, 'NORTHFIELD'),
    (94, 'OVERLAND'),
    (95, 'OVERLOOK'),
    (96, 'PARK FOREST'),
    (97, 'PARK HILL (N)'),
    (98, 'PARK HILL (S)'),
    (99, 'PARK VISTA'),
    (100, 'PARKFIELD'),
    (101, 'PARKWAY'),
    (102, 'PARKWEST'),
    (103, 'PINE RIDGE'),
    (104, 'PINE VALLEY'),
    (105, 'PINECREST'),
    (106, 'PINEHURST'),
    (107, 'PINEHURST ES S'),
    (108, 'PINEHURST ESTA'),
    (109, 'PLATTE PARK'),
    (110, 'POLO CLUB'),
    (111, 'POLO FIELD'),
    (112, 'POPLAR COVE'),
    (113, 'RANGE VIEW'),
    (114, 'REGIS'),
    (115, 'RIVER NORTH'),
    (116, 'ROSEDALE'),
    (117, 'RUBY HILL'),
    (118, 'S CHERRY CREEK'),
    (119, 'S CITY PARK'),
    (120, 'S COUNTRY CLUB'),
    (121, 'S HALE'),
    (122, 'S HARVEY PARK'),
    (123, 'S SPEER'),
    (124, 'S WASHINGTON PK'),
    (125, 'S. HILLTOP'),
    (126, 'SE CONDO'),
    (127, 'SEVEN SPRINGS'),
    (128, 'SKYLAND'),
    (129, 'SLOANS LAKE'),
    (130, 'SOUTH PLATTE'),
    (131, 'SOUTHMOOR #1'),
    (132, 'SOUTHMOOR PARK'),
    (133, 'STAPLETON'),
    (134, 'STOKES'),
    (135, 'SUMMERFIELD'),
    (136, 'SUN VALLEY'),
    (137, 'SUNNYSIDE'),
    (138, 'SWANSEA'),
    (139, 'SWANSEA (N)'),
    (140, 'SWANSEA (S)'),
    (141, 'TAMARAC HILLS'),
    (142, 'THOMAS PLACE'),
    (143, 'UNIVERSITY'),
    (144, 'UNIVERSITY HLS'),
    (145, 'UNIVERSITY PK'),
    (146, 'UNIVERSITY S'),
    (147, 'VALVERDE'),
    (148, 'VILLA PARK'),
    (149, 'VILLAS CHRY HL'),
    (150, 'VIRGINIA VALE'),
    (151, 'VIRGINIA VILL'),
    (152, 'W BAKER'),
    (153, 'W CITY PARK'),
    (154, 'W COLFAX'),
    (155, 'W GREEN VALLEY'),
    (156, 'W HIGHLAND'),
    (157, 'W HIGHLAND / HGV'),
    (158, 'W WASHINGTON PARK'),
    (159, 'W WASHINGTON PK'),
    (160, 'WASHINGTON'),
    (161, 'WASHINGTON PK'),
    (162, 'WELLSHIRE EAST'),
    (163, 'WESTBRIDGE'),
    (164, 'WESTWOOD'),
    (165, 'WHITTIER'),
    (166, 'WILLOW POINT E'),
    (167, 'WINDSOR'),
    (168, 'WLSHR/S HILLS'),
    (169, 'WOODSTREAM'),
    (170, 'ZUNI PARK');
